### ISSUE TITLE
Very basic input typing causes nodes count to increase

### ISSUE THREAD

**Issue by tenbits** [samccone/drool#1] opened 2015-07-17 15:56 UTC
Hi Sam, 

I was playing around with the module, and stumbled a leak of nodes no one can explain. Do you have any ideas about? 
Consider this template (https://github.com/tenbits/leaky/blob/master/test/input/index.html) and the runner (https://github.com/tenbits/leaky/blob/master/test/input/index.js). 
As you can see, we just type a word into the input and clean it on enter. Every iteration causes 1 node-leak on `e.target.value = str_EMPTY;`

```
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36
{"documents":1,"jsEventListeners":1,"jsHeapSizeUsed":1231344,"nodes":13}
{"documents":1,"jsEventListeners":1,"jsHeapSizeUsed":1732484,"nodes":23}
Iterations: 10, Leaks: 10
```
```
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2457.0 Safari/537.36
{"documents":1,"jsEventListeners":1,"jsHeapSizeUsed":2101496,"nodes":13}
{"documents":1,"jsEventListeners":1,"jsHeapSizeUsed":2897152,"nodes":23}
Iterations: 10, Leaks: 10
```

When we try manually to test the page directly via the DevTools, we get the same result, so it seems to be the browser engine issue. 

![image](https://cloud.githubusercontent.com/assets/550353/8751336/98d02ab6-2cac-11e5-8991-346c5b16ccd0.png)
> type `foo`; press enter; type `baz`; press enter; type `qux`; press enter; gc; stop;

I was just thinking how reliable is the nodes-count?

Thanks, Alex

**Comment by samccone** [comment] 2015-07-17 15:58
hey @tenbits I think there may be an issue in chrome 43 at the moment, can you try in chrome 45?

**Comment by tenbits** [comment] 2015-07-17 16:00
Sam, I have tested also in Canary 46 - also results with extra 10(`LOOP_COUNT`) nodes (

**Comment by samccone** [comment] 2015-07-17 16:02
dang, ok I will take a dive into this this afternoon, thanks for digging it, if we verify that this is a bug in chrome, we should elevate it to the chromium tracker

**Comment by samccone** [comment] 2015-07-17 20:59
hey @tenbits I added a basic input test, let me know what you think and how you think I can bring this inline with your hypothesis

**Comment by samccone** [comment] 2015-08-01 20:15
yep @tenbits this is a chrome bug hahah, fun times
https://code.google.com/p/chromium/issues/detail?id=516153&thanks=516153&ts=1438442933

**Comment by tenbits** [comment] 2015-08-02 09:52
Hi Sam, that's why I think this is a very useful tool. Thanks for doing this. With it we can ensure our applications have no memory leaks, and also the browsers do not introduce any. Hope, this will be fixed soon)

**Comment by samccone** [comment] 2016-01-22 16:30
Closing this issue because it is a non-issue in chrome and works as intended... I am going to follow up with a new ticket that will contain some mitigation strategies for this "issue".

**Closed by samccone** 2016-01-22 16:30 UTC
Labels: chrome-bug
